# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9edd0b432e8346dabc399ebcc0e7e1ac61358a20c80bb9b02cf6a8ffa4888f0e4ea9218ad94fbab116653a1359ca00b5308fe2a6f553ba093bac3b26dcb1c324

test:
  secret_key_base: fca084ac91a0bc27f037b79ba45537e18ba24c71de7bcd1318e817554841a2307430162d29b129f0e04695ddc0d204b323ac96fa8072608662dd8611e9dd05df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
